Enforce labels without third-party Action

diff --git a/.github/workflows/enforce-labels.yml b/.github/workflows/enforce-labels.yml
--- a/.github/workflows/enforce-labels.yml
+++ b/.github/workflows/enforce-labels.yml
@@ -4,14 +4,15 @@ name: Enforce PR labels
 on:
   workflow_call:
   pull_request:
-    types: [labeled, unlabeled, opened, edited, synchronize]
+    types: [labeled, unlabeled, opened, reopened, synchronize]
 jobs:
   enforce-label:
+    if: ${{ contains(github.event.*.labels.*.name, 'hold') || contains(github.event.*.labels.*.name, 'needs-qa') }}
     name: Enforce label
     runs-on: ubuntu-22.04
+
     steps:
-      - name: Enforce label
-        uses: yogevbd/enforce-label-action@a3c219da6b8fa73f6ba62b68ff09c469b3a1c024 # 2.2.2
-        with:
-          BANNED_LABELS: "hold,needs-qa"
-          BANNED_LABELS_DESCRIPTION: "PRs with the hold or needs-qa labels cannot be merged"
+      - name: Check for label
+        run: |
+          echo "PRs with the hold or needs-qa labels cannot be merged"
+          exit 1
